language: cpp
compiler: gcc

sudo: required

dist: bionic
services:
  - xvfb
addons:
  apt:
    packages:
      - qt5-default
      - qtdeclarative5-dev
      - libqt5charts5-dev

# TODO: Separate jobs for GUI and controller?
script:
  # Tests that controller unit tests pass on native
  - platformio test -e native
	# Tests that controller can be built for the target platform
	- platformio run
	# Tests that the GUI builds
  - cd gui
  - mkdir build
  - cd build
  - qmake ..
  - make
  - ./ProjectVentilatorGUI -d
  - ./ProjectVentilatorGUI -h
