/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "network_protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CommandPacket, CommandPacket, AUTO)


PB_BIND(GuiAckPacket, GuiAckPacket, AUTO)


PB_BIND(ControllerDataPacket, ControllerDataPacket, AUTO)


PB_BIND(Packet, Packet, AUTO)





